[project]
name = "dev-notes"
version = "0.1.0"
description = ""
readme = "README.md"
license = "MIT"
authors = ["Marcello Lamonaca <marcello@lamonaca.eu>"]
requires-python = ">=3.12"
dependencies = [
    "pillow>=11.3",
    "cairosvg>=2.8",
    "zensical>=0.0.3",
]
